import React, { useEffect, useState } from 'react';
import API, { setToken } from '../api';
type Sweet = { id:string; name:string; category:string; price:number; quantity:number };
export default function AdminPanel(){ const [sweets,setSweets]=useState<any[]>([]); const [editing,setEditing]=useState<string|null>(null); const [form,setForm]=useState({name:'',category:'',price:'',quantity:''});
  useEffect(()=>{ const t=localStorage.getItem('token'); if(t) setToken(t); fetchAll(); },[]);
  async function fetchAll(){ const res=await API.get('/sweets'); setSweets(res.data); }
  function startEdit(s:any){ setEditing(s._id||s.id); setForm({name:s.name,category:s.category,price:String(s.price),quantity:String(s.quantity)}); }
  async function saveEdit(id:string){ await API.put(`/sweets/${id}`, { name: form.name, category: form.category, price: Number(form.price), quantity: Number(form.quantity) }); setEditing(null); fetchAll(); }
  async function del(id:string){ if(!confirm('Delete this sweet?')) return; await API.delete(`/sweets/${id}`); fetchAll(); }
  async function create(e:any){ e.preventDefault(); await API.post('/sweets', { name: form.name, category: form.category, price: Number(form.price), quantity: Number(form.quantity) }); setForm({name:'',category:'',price:'',quantity:''}); fetchAll(); }
  return (<div style={{padding:12}}><h2>Admin Panel</h2><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><div className="card" style={{minWidth:280}}><h3>{editing? 'Edit Sweet':'Add Sweet'}</h3><form onSubmit={editing? (e)=>{e.preventDefault(); saveEdit(editing)} : create}><input placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input placeholder="Price" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input placeholder="Quantity" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><button type="submit">{editing? 'Save':'Add'}</button>{editing && <button type="button" onClick={()=>setEditing(null)}>Cancel</button>}</form></div><div style={{flex:1,minWidth:280}}><h3>Existing Sweets</h3><div style={{display:'grid',gap:8}}>{sweets.map(s=> (<div key={s._id||s.id} className="card" style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><strong>{s.name}</strong><div>{s.category} • ₹{s.price} • Stock: {s.quantity}</div></div><div style={{display:'flex',gap:8}}><button onClick={()=>startEdit(s)}>Edit</button><button onClick={()=>del(s._id||s.id)}>Delete</button></div></div>))}</div></div></div></div>); }
